<select class="form-select select2" id="countryCode" name="countryCode">
    <option value="" selected disabled>Select Code</option>
    <option @selected($site_data?->country_code == '+1')  value="+1">+1</option>
    <option @selected($site_data?->country_code == '+7')  value="+7">+7</option>
    <option @selected($site_data?->country_code == '+20')  value="+20">+20</option>
    <option @selected($site_data?->country_code == '+27')  value="+27">+27</option>
    <option @selected($site_data?->country_code == '+30')  value="+30">+30</option>
    <option @selected($site_data?->country_code == '+31')  value="+31">+31</option>
    <option @selected($site_data?->country_code == '+32')  value="+32">+32</option>
    <option @selected($site_data?->country_code == '+33')  value="+33">+33</option>
    <option @selected($site_data?->country_code == '+34')  value="+34">+34</option>
    <option @selected($site_data?->country_code == '+36')  value="+36">+36</option>
    <option @selected($site_data?->country_code == '+39')  value="+39">+39</option>
    <option @selected($site_data?->country_code == '+40')  value="+40">+40</option>
    <option @selected($site_data?->country_code == '+41')  value="+41">+41</option>
    <option @selected($site_data?->country_code == '+43')  value="+43">+43</option>
    <option @selected($site_data?->country_code == '+44')  value="+44">+44</option>
    <option @selected($site_data?->country_code == '+45')  value="+45">+45</option>
    <option @selected($site_data?->country_code == '+46')  value="+46">+46</option>
    <option @selected($site_data?->country_code == '+47')  value="+47">+47</option>
    <option @selected($site_data?->country_code == '+48')  value="+48">+48</option>
    <option @selected($site_data?->country_code == '+49')  value="+49">+49</option>
    <option @selected($site_data?->country_code == '+51')  value="+51">+51</option>
    <option @selected($site_data?->country_code == '+52')  value="+52">+52</option>
    <option @selected($site_data?->country_code == '+53')  value="+53">+53</option>
    <option @selected($site_data?->country_code == '+54')  value="+54">+54</option>
    <option @selected($site_data?->country_code == '+55')  value="+55">+55</option>
    <option @selected($site_data?->country_code == '+56')  value="+56">+56</option>
    <option @selected($site_data?->country_code == '+57')  value="+57">+57</option>
    <option @selected($site_data?->country_code == '+58')  value="+58">+58</option>
    <option @selected($site_data?->country_code == '+60')  value="+60">+60</option>
    <option @selected($site_data?->country_code == '+61')  value="+61">+61</option>
    <option @selected($site_data?->country_code == '+62')  value="+62">+62</option>
    <option @selected($site_data?->country_code == '+63')  value="+63">+63</option>
    <option @selected($site_data?->country_code == '+64')  value="+64">+64</option>
    <option @selected($site_data?->country_code == '+65')  value="+65">+65</option>
    <option @selected($site_data?->country_code == '+66')  value="+66">+66</option>
    <option @selected($site_data?->country_code == '+81')  value="+81">+81</option>
    <option @selected($site_data?->country_code == '+82')  value="+82">+82</option>
    <option @selected($site_data?->country_code == '+84')  value="+84">+84</option>
    <option @selected($site_data?->country_code == '+86')  value="+86">+86</option>
    <option @selected($site_data?->country_code == '+90')  value="+90">+90</option>
    <option @selected($site_data?->country_code == '+91')  value="+91">+91</option>
    <option @selected($site_data?->country_code == '+92')  value="+92">+92</option>
    <option @selected($site_data?->country_code == '+93')  value="+93">+93</option>
    <option @selected($site_data?->country_code == '+94')  value="+94">+94</option>
    <option @selected($site_data?->country_code == '+95')  value="+95">+95</option>
    <option @selected($site_data?->country_code == '+98')  value="+98">+98</option>
    <option @selected($site_data?->country_code == '+211')  value="+211">+211</option>
    <option @selected($site_data?->country_code == '+212')  value="+212">+212</option>
    <option @selected($site_data?->country_code == '+213')  value="+213">+213</option>
    <option @selected($site_data?->country_code == '+216')  value="+216">+216</option>
    <option @selected($site_data?->country_code == '+218')  value="+218">+218</option>
    <option @selected($site_data?->country_code == '+220')  value="+220">+220</option>
    <option @selected($site_data?->country_code == '+221')  value="+221">+221</option>
    <option @selected($site_data?->country_code == '+222')  value="+222">+222</option>
    <option @selected($site_data?->country_code == '+223')  value="+223">+223</option>
    <option @selected($site_data?->country_code == '+224')  value="+224">+224</option>
    <option @selected($site_data?->country_code == '+225')  value="+225">+225</option>
    <option @selected($site_data?->country_code == '+226')  value="+226">+226</option>
    <option @selected($site_data?->country_code == '+227')  value="+227">+227</option>
    <option @selected($site_data?->country_code == '+228')  value="+228">+228</option>
    <option @selected($site_data?->country_code == '+229')  value="+229">+229</option>
    <option @selected($site_data?->country_code == '+230')  value="+230">+230</option>
    <option @selected($site_data?->country_code == '+231')  value="+231">+231</option>
    <option @selected($site_data?->country_code == '+232')  value="+232">+232</option>
    <option @selected($site_data?->country_code == '+233')  value="+233">+233</option>
    <option @selected($site_data?->country_code == '+234')  value="+234">+234</option>
    <option @selected($site_data?->country_code == '+235')  value="+235">+235</option>
    <option @selected($site_data?->country_code == '+236')  value="+236">+236</option>
    <option @selected($site_data?->country_code == '+237')  value="+237">+237</option>
    <option @selected($site_data?->country_code == '+238')  value="+238">+238</option>
    <option @selected($site_data?->country_code == '+239')  value="+239">+239</option>
    <option @selected($site_data?->country_code == '+240')  value="+240">+240</option>
    <option @selected($site_data?->country_code == '+241')  value="+241">+241</option>
    <option @selected($site_data?->country_code == '+242')  value="+242">+242</option>
    <option @selected($site_data?->country_code == '+243')  value="+243">+243</option>
    <option @selected($site_data?->country_code == '+244')  value="+244">+244</option>
    <option @selected($site_data?->country_code == '+245')  value="+245">+245</option>
    <option @selected($site_data?->country_code == '+246')  value="+246">+246</option>
    <option @selected($site_data?->country_code == '+248')  value="+248">+248</option>
    <option @selected($site_data?->country_code == '+249')  value="+249">+249</option>
    <option @selected($site_data?->country_code == '+250')  value="+250">+250</option>
    <option @selected($site_data?->country_code == '+251')  value="+251">+251</option>
    <option @selected($site_data?->country_code == '+252')  value="+252">+252</option>
    <option @selected($site_data?->country_code == '+253')  value="+253">+253</option>
    <option @selected($site_data?->country_code == '+254')  value="+254">+254</option>
    <option @selected($site_data?->country_code == '+255')  value="+255">+255</option>
    <option @selected($site_data?->country_code == '+256')  value="+256">+256</option>
    <option @selected($site_data?->country_code == '+257')  value="+257">+257</option>
    <option @selected($site_data?->country_code == '+258')  value="+258">+258</option>
    <option @selected($site_data?->country_code == '+260')  value="+260">+260</option>
    <option @selected($site_data?->country_code == '+261')  value="+261">+261</option>
    <option @selected($site_data?->country_code == '+262')  value="+262">+262</option>
    <option @selected($site_data?->country_code == '+263')  value="+263">+263</option>
    <option @selected($site_data?->country_code == '+264')  value="+264">+264</option>
    <option @selected($site_data?->country_code == '+265')  value="+265">+265</option>
    <option @selected($site_data?->country_code == '+266')  value="+266">+266</option>
    <option @selected($site_data?->country_code == '+267')  value="+267">+267</option>
    <option @selected($site_data?->country_code == '+268')  value="+268">+268</option>
    <option @selected($site_data?->country_code == '+269')  value="+269">+269</option>
    <option @selected($site_data?->country_code == '+290')  value="+290">+290</option>
    <option @selected($site_data?->country_code == '+291')  value="+291">+291</option>
    <option @selected($site_data?->country_code == '+297')  value="+297">+297</option>
    <option @selected($site_data?->country_code == '+298')  value="+298">+298</option>
    <option @selected($site_data?->country_code == '+299')  value="+299">+299</option>
    <option @selected($site_data?->country_code == '+350')  value="+350">+350</option>
    <option @selected($site_data?->country_code == '+351')  value="+351">+351</option>
    <option @selected($site_data?->country_code == '+352')  value="+352">+352</option>
    <option @selected($site_data?->country_code == '+353')  value="+353">+353</option>
    <option @selected($site_data?->country_code == '+354')  value="+354">+354</option>
    <option @selected($site_data?->country_code == '+355')  value="+355">+355</option>
    <option @selected($site_data?->country_code == '+356')  value="+356">+356</option>
    <option @selected($site_data?->country_code == '+357')  value="+357">+357</option>
    <option @selected($site_data?->country_code == '+358')  value="+358">+358</option>
    <option @selected($site_data?->country_code == '+359')  value="+359">+359</option>
    <option @selected($site_data?->country_code == '+370')  value="+370">+370</option>
    <option @selected($site_data?->country_code == '+371')  value="+371">+371</option>
    <option @selected($site_data?->country_code == '+372')  value="+372">+372</option>
    <option @selected($site_data?->country_code == '+373')  value="+373">+373</option>
    <option @selected($site_data?->country_code == '+374')  value="+374">+374</option>
    <option @selected($site_data?->country_code == '+375')  value="+375">+375</option>
    <option @selected($site_data?->country_code == '+376')  value="+376">+376</option>
    <option @selected($site_data?->country_code == '+377')  value="+377">+377</option>
    <option @selected($site_data?->country_code == '+378')  value="+378">+378</option>
    <option @selected($site_data?->country_code == '+379')  value="+379">+379</option>
    <option @selected($site_data?->country_code == '+380')  value="+380">+380</option>
    <option @selected($site_data?->country_code == '+381')  value="+381">+381</option>
    <option @selected($site_data?->country_code == '+382')  value="+382">+382</option>
    <option @selected($site_data?->country_code == '+383')  value="+383">+383</option>
    <option @selected($site_data?->country_code == '+385')  value="+385">+385</option>
    <option @selected($site_data?->country_code == '+386')  value="+386">+386</option>
    <option @selected($site_data?->country_code == '+387')  value="+387">+387</option>
    <option @selected($site_data?->country_code == '+389')  value="+389">+389</option>
    <option @selected($site_data?->country_code == '+420')  value="+420">+420</option>
    <option @selected($site_data?->country_code == '+421')  value="+421">+421</option>
    <option @selected($site_data?->country_code == '+423')  value="+423">+423</option>
    <option @selected($site_data?->country_code == '+500')  value="+500">+500</option>
    <option @selected($site_data?->country_code == '+501')  value="+501">+501</option>
    <option @selected($site_data?->country_code == '+502')  value="+502">+502</option>
    <option @selected($site_data?->country_code == '+503')  value="+503">+503</option>
    <option @selected($site_data?->country_code == '+504')  value="+504">+504</option>
    <option @selected($site_data?->country_code == '+505')  value="+505">+505</option>
    <option @selected($site_data?->country_code == '+506')  value="+506">+506</option>
    <option @selected($site_data?->country_code == '+507')  value="+507">+507</option>
</select>
